"""Check claims about ker(mu) vs the reducible span in Lambda_n ot Lambda_n."""
from itertools import combinations

def subsets(n):
    out = []
    for r in range(n + 2):
        for S in combinations(range(n + 1), r):
            out.append(frozenset(S))
    return out

for n in range(0, 4):
    S = subsets(n)
    pairs = [(V, W) for V in S for W in S]
    red = [(V, W) for V, W in pairs if V & W]
    irr = [(V, W) for V, W in pairs if not (V & W)]
    # dim ker mu: mu surjective onto Lambda_n (dim 2^{n+1})
    dim_total, dim_lam = len(pairs), len(S)
    dim_ker = dim_total - dim_lam
    print(f"n={n}: dim(ot2)={dim_total} (4^{n+1}={4**(n+1)}), "
          f"reducible={len(red)} (4^k-3^k={4**(n+1)-3**(n+1)}), "
          f"dim ker(mu)={dim_ker} (4^k-2^k={4**(n+1)-2**(n+1)})")

# witness: x_i ot x_j + x_j ot x_i is irreducible and in ker(mu)
f = frozenset
w = [(f({0}), f({1})), (f({1}), f({0}))]
print("\nwitness x_0 ot x_1 + x_1 ot x_0:")
print("  all summands irreducible:", all(not (V & W) for V, W in w))
print("  mu-image (mod 2):", "0" if len({(V | W) for V, W in w}) == 1 else "nonzero")

# is the reducible span exactly the ideal generated by x_k ot x_k?
n = 3
S = subsets(n)
ideal = set()
for k in range(n + 1):
    for A in S:
        for B in S:
            if k not in A and k not in B:
                ideal.add((A | {k}, B | {k}))
red = {(V, W) for V in S for W in S if V & W}
print(f"\nn={n}: ideal generated by (x_k ot x_k) == reducible span basis:", ideal == red)

# adjointness of mu and Delta: monomial (Kronecker) pairing vs socle pairing
def partitions(U):
    U = sorted(U)
    out = []
    for m in range(1 << len(U)):
        A = frozenset(u for b, u in enumerate(U) if m >> b & 1)
        out.append((A, frozenset(U) - A))
    return out

n = 2
S = subsets(n)
full = frozenset(range(n + 1))
mono_ok = socle_ok = True
for V in S:
    for W in S:
        for C in S:
            lhs_mono = 1 if (not (V & W) and (V | W) == C) else 0
            rhs_mono = sum(1 for A, B in partitions(C) if A == V and B == W) % 2
            if lhs_mono != rhs_mono:
                mono_ok = False
            lhs_soc = 1 if (not (V & W) and not ((V | W) & C) and (V | W | C) == full) else 0
            rhs_soc = sum(1 for A, B in partitions(C)
                          if not (V & A) and (V | A) == full and not (W & B) and (W | B) == full) % 2
            if lhs_soc != rhs_soc:
                socle_ok = False
print(f"\nadjointness <mu(a ot b), c> = <a ot b, Delta c>:")
print(f"  under monomial (Kronecker) pairing: {mono_ok}")
print(f"  under socle pairing <x_U,x_U'>=[U cup U'=all]: {socle_ok}")

# is ker(mu) itself a subcomplex? (mu is an algebra map, so ker is an ideal)
print("\nmu(Delta omega) = 2*omega = 0, and mu is an algebra map, so ker(mu) is an ideal: subcomplex")
